sudo: required
language: generic 

services:
  - docker

before-install:
  - docker build -t neotomax/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true neotomax/docker-react npm run test